from Inter.Node import Node
from Inter.Stmt import Stmt
from Inter.If import If
from Inter.Elif import Elif
from Inter.Else import Else
from Inter.Expr import Expr
from Inter.Id import Id
from Inter.Op import Op
from Inter.Arith import Arith
from Inter.Seq import Seq
from Inter.Assign import Assign
from Inter.Paren import Paren
from Inter.Function import Function
from Inter.ElifSeq import ElifSeq
from Inter.Print import Print
from Inter.PrintErr import PrintErr
from Inter.FunctionCall import FunctionCall
from Inter.For import For
from Inter.While import While
