from Inter.Node import Node
from Inter.Stmt import Stmt
from Inter.If import If
from Inter.Else import Else
from Inter.Expr import Expr
from Inter.Id import Id
from Inter.Op import Op
from Inter.Arith import Arith
from Inter.Seq import Seq
from Inter.Assign import Assign
from Inter.Paren import Paren
